Monster Vault/app/config/routes.rb
Rails.application.routes.draw do
  resources :monsters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Monster Vault/app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Monster Vault/app/app/models/monster.rb
class Monster < ApplicationRecord
end

Monster Vault/app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Monster Vault/app/app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name, :size, :race, :subtype, :alignment, :armor_class, :hit_points, :hit_dice, :speed, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :wisdom_save, :damage_vulnerabilities, :damage_resistances, :damage_immunities, :condition_immunities, :senses, :languages, :challenge_rating, :special_abilities, :actions, :constitution_save, :perception, :history, :legendary_actions, :intelligence_save, :religion, :medicine, :stealth, :dexterity_save, :charisma_save, :persuasion, :insight, :deception, :athletics, :arcana, :nature, :acrobatics, :strength_save, :reactions, :survival, :investigation, :intimidation, :performance)
    end
end

Monster Vault/app/app/helpers/application_helper.rb
module ApplicationHelper
end

Monster Vault/app/app/helpers/monsters_helper.rb
module MonstersHelper
end

Monster Vault/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Monster Vault/app/app/views/monsters/_form.html.erb
<%= form_with(model: monster, local: true) do |form| %>
  <% if monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_area :size %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_area :race %>
  </div>

  <div class="field">
    <%= form.label :subtype %>
    <%= form.text_area :subtype %>
  </div>

  <div class="field">
    <%= form.label :alignment %>
    <%= form.text_area :alignment %>
  </div>

  <div class="field">
    <%= form.label :armor_class %>
    <%= form.text_area :armor_class %>
  </div>

  <div class="field">
    <%= form.label :hit_points %>
    <%= form.text_area :hit_points %>
  </div>

  <div class="field">
    <%= form.label :hit_dice %>
    <%= form.text_area :hit_dice %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.text_area :speed %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.text_area :strength %>
  </div>

  <div class="field">
    <%= form.label :dexterity %>
    <%= form.text_area :dexterity %>
  </div>

  <div class="field">
    <%= form.label :constitution %>
    <%= form.text_area :constitution %>
  </div>

  <div class="field">
    <%= form.label :intelligence %>
    <%= form.text_area :intelligence %>
  </div>

  <div class="field">
    <%= form.label :wisdom %>
    <%= form.text_area :wisdom %>
  </div>

  <div class="field">
    <%= form.label :charisma %>
    <%= form.text_area :charisma %>
  </div>

  <div class="field">
    <%= form.label :wisdom_save %>
    <%= form.text_area :wisdom_save %>
  </div>

  <div class="field">
    <%= form.label :damage_vulnerabilities %>
    <%= form.text_area :damage_vulnerabilities %>
  </div>

  <div class="field">
    <%= form.label :damage_resistances %>
    <%= form.text_area :damage_resistances %>
  </div>

  <div class="field">
    <%= form.label :damage_immunities %>
    <%= form.text_area :damage_immunities %>
  </div>

  <div class="field">
    <%= form.label :condition_immunities %>
    <%= form.text_area :condition_immunities %>
  </div>

  <div class="field">
    <%= form.label :senses %>
    <%= form.text_area :senses %>
  </div>

  <div class="field">
    <%= form.label :languages %>
    <%= form.text_area :languages %>
  </div>

  <div class="field">
    <%= form.label :challenge_rating %>
    <%= form.text_area :challenge_rating %>
  </div>

  <div class="field">
    <%= form.label :special_abilities %>
    <%= form.text_area :special_abilities %>
  </div>

  <div class="field">
    <%= form.label :actions %>
    <%= form.text_area :actions %>
  </div>

  <div class="field">
    <%= form.label :constitution_save %>
    <%= form.text_area :constitution_save %>
  </div>

  <div class="field">
    <%= form.label :perception %>
    <%= form.text_area :perception %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.text_area :history %>
  </div>

  <div class="field">
    <%= form.label :legendary_actions %>
    <%= form.text_area :legendary_actions %>
  </div>

  <div class="field">
    <%= form.label :intelligence_save %>
    <%= form.text_area :intelligence_save %>
  </div>

  <div class="field">
    <%= form.label :religion %>
    <%= form.text_area :religion %>
  </div>

  <div class="field">
    <%= form.label :medicine %>
    <%= form.text_area :medicine %>
  </div>

  <div class="field">
    <%= form.label :stealth %>
    <%= form.text_area :stealth %>
  </div>

  <div class="field">
    <%= form.label :dexterity_save %>
    <%= form.text_area :dexterity_save %>
  </div>

  <div class="field">
    <%= form.label :charisma_save %>
    <%= form.text_area :charisma_save %>
  </div>

  <div class="field">
    <%= form.label :persuasion %>
    <%= form.text_area :persuasion %>
  </div>

  <div class="field">
    <%= form.label :insight %>
    <%= form.text_area :insight %>
  </div>

  <div class="field">
    <%= form.label :deception %>
    <%= form.text_area :deception %>
  </div>

  <div class="field">
    <%= form.label :athletics %>
    <%= form.text_area :athletics %>
  </div>

  <div class="field">
    <%= form.label :arcana %>
    <%= form.text_area :arcana %>
  </div>

  <div class="field">
    <%= form.label :nature %>
    <%= form.text_area :nature %>
  </div>

  <div class="field">
    <%= form.label :acrobatics %>
    <%= form.text_area :acrobatics %>
  </div>

  <div class="field">
    <%= form.label :strength_save %>
    <%= form.text_area :strength_save %>
  </div>

  <div class="field">
    <%= form.label :reactions %>
    <%= form.text_area :reactions %>
  </div>

  <div class="field">
    <%= form.label :survival %>
    <%= form.text_area :survival %>
  </div>

  <div class="field">
    <%= form.label :investigation %>
    <%= form.text_area :investigation %>
  </div>

  <div class="field">
    <%= form.label :intimidation %>
    <%= form.text_area :intimidation %>
  </div>

  <div class="field">
    <%= form.label :performance %>
    <%= form.text_area :performance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Monster Vault/app/app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

Monster Vault/app/app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monsters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Race</th>
      <th>Subtype</th>
      <th>Alignment</th>
      <th>Armor class</th>
      <th>Hit points</th>
      <th>Hit dice</th>
      <th>Speed</th>
      <th>Strength</th>
      <th>Dexterity</th>
      <th>Constitution</th>
      <th>Intelligence</th>
      <th>Wisdom</th>
      <th>Charisma</th>
      <th>Wisdom save</th>
      <th>Damage vulnerabilities</th>
      <th>Damage resistances</th>
      <th>Damage immunities</th>
      <th>Condition immunities</th>
      <th>Senses</th>
      <th>Languages</th>
      <th>Challenge rating</th>
      <th>Special abilities</th>
      <th>Actions</th>
      <th>Constitution save</th>
      <th>Perception</th>
      <th>History</th>
      <th>Legendary actions</th>
      <th>Intelligence save</th>
      <th>Religion</th>
      <th>Medicine</th>
      <th>Stealth</th>
      <th>Dexterity save</th>
      <th>Charisma save</th>
      <th>Persuasion</th>
      <th>Insight</th>
      <th>Deception</th>
      <th>Athletics</th>
      <th>Arcana</th>
      <th>Nature</th>
      <th>Acrobatics</th>
      <th>Strength save</th>
      <th>Reactions</th>
      <th>Survival</th>
      <th>Investigation</th>
      <th>Intimidation</th>
      <th>Performance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.size %></td>
        <td><%= monster.race %></td>
        <td><%= monster.subtype %></td>
        <td><%= monster.alignment %></td>
        <td><%= monster.armor_class %></td>
        <td><%= monster.hit_points %></td>
        <td><%= monster.hit_dice %></td>
        <td><%= monster.speed %></td>
        <td><%= monster.strength %></td>
        <td><%= monster.dexterity %></td>
        <td><%= monster.constitution %></td>
        <td><%= monster.intelligence %></td>
        <td><%= monster.wisdom %></td>
        <td><%= monster.charisma %></td>
        <td><%= monster.wisdom_save %></td>
        <td><%= monster.damage_vulnerabilities %></td>
        <td><%= monster.damage_resistances %></td>
        <td><%= monster.damage_immunities %></td>
        <td><%= monster.condition_immunities %></td>
        <td><%= monster.senses %></td>
        <td><%= monster.languages %></td>
        <td><%= monster.challenge_rating %></td>
        <td><%= monster.special_abilities %></td>
        <td><%= monster.actions %></td>
        <td><%= monster.constitution_save %></td>
        <td><%= monster.perception %></td>
        <td><%= monster.history %></td>
        <td><%= monster.legendary_actions %></td>
        <td><%= monster.intelligence_save %></td>
        <td><%= monster.religion %></td>
        <td><%= monster.medicine %></td>
        <td><%= monster.stealth %></td>
        <td><%= monster.dexterity_save %></td>
        <td><%= monster.charisma_save %></td>
        <td><%= monster.persuasion %></td>
        <td><%= monster.insight %></td>
        <td><%= monster.deception %></td>
        <td><%= monster.athletics %></td>
        <td><%= monster.arcana %></td>
        <td><%= monster.nature %></td>
        <td><%= monster.acrobatics %></td>
        <td><%= monster.strength_save %></td>
        <td><%= monster.reactions %></td>
        <td><%= monster.survival %></td>
        <td><%= monster.investigation %></td>
        <td><%= monster.intimidation %></td>
        <td><%= monster.performance %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster', new_monster_path %>

Monster Vault/app/app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Back', monsters_path %>

Monster Vault/app/app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @monster.size %>
</p>

<p>
  <strong>Race:</strong>
  <%= @monster.race %>
</p>

<p>
  <strong>Subtype:</strong>
  <%= @monster.subtype %>
</p>

<p>
  <strong>Alignment:</strong>
  <%= @monster.alignment %>
</p>

<p>
  <strong>Armor class:</strong>
  <%= @monster.armor_class %>
</p>

<p>
  <strong>Hit points:</strong>
  <%= @monster.hit_points %>
</p>

<p>
  <strong>Hit dice:</strong>
  <%= @monster.hit_dice %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @monster.speed %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @monster.strength %>
</p>

<p>
  <strong>Dexterity:</strong>
  <%= @monster.dexterity %>
</p>

<p>
  <strong>Constitution:</strong>
  <%= @monster.constitution %>
</p>

<p>
  <strong>Intelligence:</strong>
  <%= @monster.intelligence %>
</p>

<p>
  <strong>Wisdom:</strong>
  <%= @monster.wisdom %>
</p>

<p>
  <strong>Charisma:</strong>
  <%= @monster.charisma %>
</p>

<p>
  <strong>Wisdom save:</strong>
  <%= @monster.wisdom_save %>
</p>

<p>
  <strong>Damage vulnerabilities:</strong>
  <%= @monster.damage_vulnerabilities %>
</p>

<p>
  <strong>Damage resistances:</strong>
  <%= @monster.damage_resistances %>
</p>

<p>
  <strong>Damage immunities:</strong>
  <%= @monster.damage_immunities %>
</p>

<p>
  <strong>Condition immunities:</strong>
  <%= @monster.condition_immunities %>
</p>

<p>
  <strong>Senses:</strong>
  <%= @monster.senses %>
</p>

<p>
  <strong>Languages:</strong>
  <%= @monster.languages %>
</p>

<p>
  <strong>Challenge rating:</strong>
  <%= @monster.challenge_rating %>
</p>

<p>
  <strong>Special abilities:</strong>
  <%= @monster.special_abilities %>
</p>

<p>
  <strong>Actions:</strong>
  <%= @monster.actions %>
</p>

<p>
  <strong>Constitution save:</strong>
  <%= @monster.constitution_save %>
</p>

<p>
  <strong>Perception:</strong>
  <%= @monster.perception %>
</p>

<p>
  <strong>History:</strong>
  <%= @monster.history %>
</p>

<p>
  <strong>Legendary actions:</strong>
  <%= @monster.legendary_actions %>
</p>

<p>
  <strong>Intelligence save:</strong>
  <%= @monster.intelligence_save %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @monster.religion %>
</p>

<p>
  <strong>Medicine:</strong>
  <%= @monster.medicine %>
</p>

<p>
  <strong>Stealth:</strong>
  <%= @monster.stealth %>
</p>

<p>
  <strong>Dexterity save:</strong>
  <%= @monster.dexterity_save %>
</p>

<p>
  <strong>Charisma save:</strong>
  <%= @monster.charisma_save %>
</p>

<p>
  <strong>Persuasion:</strong>
  <%= @monster.persuasion %>
</p>

<p>
  <strong>Insight:</strong>
  <%= @monster.insight %>
</p>

<p>
  <strong>Deception:</strong>
  <%= @monster.deception %>
</p>

<p>
  <strong>Athletics:</strong>
  <%= @monster.athletics %>
</p>

<p>
  <strong>Arcana:</strong>
  <%= @monster.arcana %>
</p>

<p>
  <strong>Nature:</strong>
  <%= @monster.nature %>
</p>

<p>
  <strong>Acrobatics:</strong>
  <%= @monster.acrobatics %>
</p>

<p>
  <strong>Strength save:</strong>
  <%= @monster.strength_save %>
</p>

<p>
  <strong>Reactions:</strong>
  <%= @monster.reactions %>
</p>

<p>
  <strong>Survival:</strong>
  <%= @monster.survival %>
</p>

<p>
  <strong>Investigation:</strong>
  <%= @monster.investigation %>
</p>

<p>
  <strong>Intimidation:</strong>
  <%= @monster.intimidation %>
</p>

<p>
  <strong>Performance:</strong>
  <%= @monster.performance %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>